// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package server

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComPsfproMetricsInternalServer(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Address = string(in.String())
		case "restore":
			out.Restore = bool(in.Bool())
		case "store_interval":
			out.StoreInterval = int64(in.Int64())
		case "store_file":
			out.StoragePath = string(in.String())
		case "database_dsn":
			out.DatabaseDsn = string(in.String())
		case "hash_key":
			out.HashKey = string(in.String())
		case "crypto_key":
			out.CryptoKey = string(in.String())
		case "trusted_subnet":
			out.TrustedSubnet = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComPsfproMetricsInternalServer(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"restore\":"
		out.RawString(prefix)
		out.Bool(bool(in.Restore))
	}
	{
		const prefix string = ",\"store_interval\":"
		out.RawString(prefix)
		out.Int64(int64(in.StoreInterval))
	}
	{
		const prefix string = ",\"store_file\":"
		out.RawString(prefix)
		out.String(string(in.StoragePath))
	}
	{
		const prefix string = ",\"database_dsn\":"
		out.RawString(prefix)
		out.String(string(in.DatabaseDsn))
	}
	{
		const prefix string = ",\"hash_key\":"
		out.RawString(prefix)
		out.String(string(in.HashKey))
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		out.String(string(in.CryptoKey))
	}
	{
		const prefix string = ",\"trusted_subnet\":"
		out.RawString(prefix)
		out.String(string(in.TrustedSubnet))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComPsfproMetricsInternalServer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComPsfproMetricsInternalServer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComPsfproMetricsInternalServer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComPsfproMetricsInternalServer(l, v)
}
