// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package agent

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComPsfproMetricsInternalAgent(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.ServerAddress = string(in.String())
		case "report_interval":
			out.ReportInterval = int64(in.Int64())
		case "poll_interval":
			out.PollInterval = int64(in.Int64())
		case "rate_limit":
			out.RateLimit = int64(in.Int64())
		case "hash_key":
			out.HashKey = string(in.String())
		case "crypto_key":
			out.CryptoKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComPsfproMetricsInternalAgent(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServerAddress))
	}
	{
		const prefix string = ",\"report_interval\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReportInterval))
	}
	{
		const prefix string = ",\"poll_interval\":"
		out.RawString(prefix)
		out.Int64(int64(in.PollInterval))
	}
	{
		const prefix string = ",\"rate_limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.RateLimit))
	}
	{
		const prefix string = ",\"hash_key\":"
		out.RawString(prefix)
		out.String(string(in.HashKey))
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		out.String(string(in.CryptoKey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComPsfproMetricsInternalAgent(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComPsfproMetricsInternalAgent(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComPsfproMetricsInternalAgent(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComPsfproMetricsInternalAgent(l, v)
}
